//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacadeFor3e.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacadeFor3e.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;@odata.context&quot;: &quot;https://rdfin91tewa01.elite.global/TE_3E_DEV_EU_REPORT/odata/$metadata#Proforma_ndt(ProfPresParagraphs)&quot;,
        ///  &quot;value&quot;: [
        ///    {
        ///      &quot;ProfPresParagraphs&quot;: [
        ///        {
        ///          &quot;ProfPresentationParagraphID&quot;: &quot;cc75bc73-f072-4cd4-9166-013dc8b8109c&quot;,
        ///          &quot;ArchetypeCode&quot;: &quot;ProfPresentationParagraph&quot;,
        ///          &quot;LastProcItemID&quot;: &quot;c56a8cd3-374a-4089-be70-71b366b6285f&quot;,
        ///          &quot;OrigProcItemID&quot;: &quot;c56a8cd3-374a-4089-be70-71b366b6285f&quot;,
        ///          &quot;HasAttachments&quot;: false,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleProfPresParagraphs {
            get {
                return ResourceManager.GetString("ExampleProfPresParagraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcessExecutionResults Result=&quot;Failure&quot; Message=&quot;Error attempting to read data.&quot;&gt;
        ///	&lt;MAIN&gt;
        ///		&lt;ERROR Context=&quot;&quot;&gt;
        ///			&lt;MESSAGE&gt;
        ///				An error occurred in the Framework: The element &apos;Attributes&apos; in namespace &apos;http://elite.com/schemas/transaction/object/write/Proforma&apos; has invalid child element &apos;ProfStatusx&apos; in namespace &apos;http://elite.com/schemas/transaction/object/write/Proforma&apos;. List of possible elements expected: &apos;ProfIndex, ProfDate, BillingGroup, TimeStart, TimeEnd, CostStart, CostEnd, ChargeStart, Cha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseForError {
            get {
                return ResourceManager.GetString("ExampleResponseForError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcessExecutionResults Process=&quot;ProfMaster&quot; Result=&quot;Interface&quot; StepId=&quot;Display&quot; Records=&quot;1&quot; User=&quot;Jon Saffron&quot; Name=&quot;X   Proforma Edit&quot; ProcessItemId=&quot;7168b5ba-d21e-4133-bffa-41fe81d2046d&quot;&gt;
        ///	&lt;Keys&gt;
        ///		&lt;Proforma KeyValue=&quot;215960&quot; /&gt;
        ///	&lt;/Keys&gt;
        ///	&lt;TimingInfo&gt;
        ///		&lt;ProcessCreation&gt;00:00:00.2762058&lt;/ProcessCreation&gt;
        ///		&lt;DataCollectionCreation&gt;00:00:28.8805284&lt;/DataCollectionCreation&gt;
        ///		&lt;ProcessRun&gt;00:00:00.3008735&lt;/ProcessRun&gt;
        ///		&lt;WriteResults&gt;00:00:00.0306075&lt;/WriteResults&gt;
        ///		&lt;TotalTime&gt;00:00:29.4882152&lt;/To [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseInterfaceOnLockedRecord {
            get {
                return ResourceManager.GetString("ExampleResponseInterfaceOnLockedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcessExecutionResults Process=&quot;ProfMaster_ndt&quot; Result=&quot;Success&quot; OutputId=&quot;Success&quot; Records=&quot;1&quot; User=&quot;Jon Saffron&quot; Name=&quot;Proforma Edit (Nth Degree)&quot; ProcessItemId=&quot;37c20f6d-680b-4107-a8ee-70a0c2d4616f&quot;&gt;
        ///	&lt;Keys&gt;
        ///		&lt;Proforma KeyValue=&quot;215946&quot; /&gt;
        ///	&lt;/Keys&gt;
        ///	&lt;TimingInfo&gt;
        ///		&lt;ProcessCreation&gt;00:00:00.3853547&lt;/ProcessCreation&gt;
        ///		&lt;DataCollectionCreation&gt;00:00:08.2564371&lt;/DataCollectionCreation&gt;
        ///		&lt;ProcessRun&gt;00:00:05.0203943&lt;/ProcessRun&gt;
        ///		&lt;WriteResults&gt;00:00:00.0003845&lt;/WriteResults&gt;
        ///		&lt;TotalTime&gt;00:00:1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseSuccessOnLockedRecord {
            get {
                return ResourceManager.GetString("ExampleResponseSuccessOnLockedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcessExecutionResults Process=&quot;ProfMaster_ndt&quot; Result=&quot;Success&quot; OutputId=&quot;Success&quot; Records=&quot;1&quot; User=&quot;Jon Saffron&quot; Name=&quot;Proforma Edit (Nth Degree)&quot; ProcessItemId=&quot;fc2ce60a-5f75-4de2-a799-8a07c4997668&quot;&gt;
        ///	&lt;Keys&gt;
        ///		&lt;Proforma KeyValue=&quot;215966&quot; /&gt;
        ///	&lt;/Keys&gt;
        ///	&lt;TimingInfo&gt;
        ///		&lt;ProcessCreation&gt;00:00:00.2837098&lt;/ProcessCreation&gt;
        ///		&lt;DataCollectionCreation&gt;00:00:05.1744501&lt;/DataCollectionCreation&gt;
        ///		&lt;ProcessRun&gt;00:00:09.8868126&lt;/ProcessRun&gt;
        ///		&lt;WriteResults&gt;00:00:00&lt;/WriteResults&gt;
        ///		&lt;TotalTime&gt;00:00:15.344972 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseSuccessWithKeyInfo {
            get {
                return ResourceManager.GetString("ExampleResponseSuccessWithKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcessExecutionResults Process=&quot;ProfMaster_ndt&quot; Result=&quot;Success&quot; OutputId=&quot;Success&quot; Records=&quot;1&quot; User=&quot;Jon Saffron&quot; Name=&quot;Proforma Edit (Nth Degree)&quot; ProcessItemId=&quot;84647d6b-a173-4e10-a271-7e42394ef600&quot;&gt;
        ///	&lt;TimingInfo&gt;
        ///		&lt;ProcessCreation&gt;00:00:00.2364574&lt;/ProcessCreation&gt;
        ///		&lt;DataCollectionCreation&gt;00:00:04.7170214&lt;/DataCollectionCreation&gt;
        ///		&lt;ProcessRun&gt;00:00:09.4814444&lt;/ProcessRun&gt;
        ///		&lt;WriteResults&gt;00:00:00.0001367&lt;/WriteResults&gt;
        ///		&lt;TotalTime&gt;00:00:14.4350599&lt;/TotalTime&gt;
        ///	&lt;/TimingInfo&gt;
        ///&lt;/ProcessExecu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseSuccessWithoutKeyInfo {
            get {
                return ResourceManager.GetString("ExampleResponseSuccessWithoutKeyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcessExecutionResults Process=&quot;ProfMaster_ndt&quot; Result=&quot;Success&quot; OutputId=&quot;Failure&quot; Records=&quot;1&quot; User=&quot;Jon Saffron&quot; Name=&quot;Proforma Edit (ndt)&quot; ProcessItemId=&quot;3f032f59-bc39-420c-b7dc-248536beb3ad&quot;&gt;
        ///  &lt;Keys&gt;
        ///    &lt;Proforma KeyValue=&quot;516557&quot; /&gt;
        ///  &lt;/Keys&gt;
        ///  &lt;TimingInfo&gt;
        ///    &lt;ProcessCreation&gt;00:00:00.0468730&lt;/ProcessCreation&gt;
        ///    &lt;DataCollectionCreation&gt;00:00:01.1876069&lt;/DataCollectionCreation&gt;
        ///    &lt;ProcessRun&gt;00:00:00.4375344&lt;/ProcessRun&gt;
        ///    &lt;WriteResults&gt;00:00:00&lt;/WriteResults&gt;
        ///    &lt;TotalTime&gt;00:00:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseWithDataErrors {
            get {
                return ResourceManager.GetString("ExampleResponseWithDataErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcessExecutionResults Process=&quot;ProfMaster&quot; Result=&quot;Interface&quot; StepId=&quot;Display&quot; Records=&quot;1&quot; User=&quot;Jon Saffron&quot; Name=&quot;X   Proforma Edit&quot; ProcessItemId=&quot;01b86388-1d6c-420f-9b3c-e059635c4af4&quot;&gt;
        ///	&lt;Keys&gt;
        ///		&lt;Proforma KeyValue=&quot;215951&quot; /&gt;
        ///	&lt;/Keys&gt;
        ///	&lt;TimingInfo&gt;
        ///		&lt;ProcessCreation&gt;00:00:00.2887448&lt;/ProcessCreation&gt;
        ///		&lt;DataCollectionCreation&gt;00:02:05.0831522&lt;/DataCollectionCreation&gt;
        ///		&lt;ProcessRun&gt;00:00:00.2634079&lt;/ProcessRun&gt;
        ///		&lt;WriteResults&gt;00:00:00&lt;/WriteResults&gt;
        ///		&lt;TotalTime&gt;00:02:05.6353049&lt;/TotalTime&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseWithMessage {
            get {
                return ResourceManager.GetString("ExampleResponseWithMessage", resourceCulture);
            }
        }
    }
}
