//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacadeFor3e.TransactionService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", ConfigurationName="FacadeFor3e.TransactionService.TransactionServiceSoap")]
    internal interface TransactionServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/ExposeEnum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacadeFor3e.TransactionService.ReturnInfoType ExposeEnum(string processXML, int returnInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/ExposeEnum", ReplyAction="*")]
        System.Threading.Tasks.Task<FacadeFor3e.TransactionService.ReturnInfoType> ExposeEnumAsync(string processXML, int returnInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetServiceTimeZoneID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetServiceTimeZoneID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetServiceTimeZoneID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetServiceTimeZoneIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetServiceCulture", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetServiceCulture();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetServiceCulture", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetServiceCultureAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/ExecuteProcess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ExecuteProcess(string processXML, int returnInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/ExecuteProcess", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ExecuteProcessAsync(string processXML, int returnInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetAppObjectSecurityRights", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAppObjectSecurityRights(string projectXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetAppObjectSecurityRights", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetAppObjectSecurityRightsAsync(string projectXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/CancelAllOpenProcesses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelAllOpenProcesses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/CancelAllOpenProcesses", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CancelAllOpenProcessesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetArchetypeDataGlobal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetArchetypeDataGlobal(string selectXml, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetArchetypeDataGlobal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetArchetypeDataGlobalAsync(string selectXml, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMetricDataGlobal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMetricDataGlobal(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMetricDataGlobal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMetricDataGlobalAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetNamedMetricDataGlobal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNamedMetricDataGlobal(string selectXml, string metricTableName, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetNamedMetricDataGlobal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNamedMetricDataGlobalAsync(string selectXml, string metricTableName, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetFormattedArchetypeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFormattedArchetypeData(string selectXml, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetFormattedArchetypeData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFormattedArchetypeDataAsync(string selectXml, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetArchetypeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetArchetypeData(string selectXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetArchetypeData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetArchetypeDataAsync(string selectXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetFormattedMetricData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFormattedMetricData(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetFormattedMetricData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFormattedMetricDataAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMetricData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMetricData(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMetricData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMetricDataAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetFormattedNamedMetricData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFormattedNamedMetricData(string selectXml, string metricTableName, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetFormattedNamedMetricData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetFormattedNamedMetricDataAsync(string selectXml, string metricTableName, string delimiterChar, bool includeHeaders);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetNamedMetricData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNamedMetricData(string selectXml, string metricTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetNamedMetricData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNamedMetricDataAsync(string selectXml, string metricTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetArchetypeDataSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetArchetypeDataSQL(string selectXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetArchetypeDataSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetArchetypeDataSQLAsync(string selectXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMetricDataSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMetricDataSQL(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMetricDataSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMetricDataSQLAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetNamedMetricDataSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetNamedMetricDataSQL(string selectXml, string metricTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetNamedMetricDataSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetNamedMetricDataSQLAsync(string selectXml, string metricTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetData(string reportQueryXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDataAsync(string reportQueryXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetDataFromReportLayout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataFromReportLayout(string reportLayoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetDataFromReportLayout", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDataFromReportLayoutAsync(string reportLayoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetDataFromReportLayoutCrystal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataFromReportLayoutCrystal(string reportLayoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetDataFromReportLayoutCrystal", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDataFromReportLayoutCrystalAsync(string reportLayoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetSyncIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSyncIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetSyncIds", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetSyncIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/CheckFileHash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckFileHash(string syncId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/CheckFileHash", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckFileHashAsync(string syncId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/Ping", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/Ping", ReplyAction="*")]
        System.Threading.Tasks.Task PingAsync();
        
        // CODEGEN: Parameter 'buffer' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/SendAttachmentChunk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacadeFor3e.TransactionService.SendAttachmentChunkResponse SendAttachmentChunk(FacadeFor3e.TransactionService.SendAttachmentChunkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/SendAttachmentChunk", ReplyAction="*")]
        System.Threading.Tasks.Task<FacadeFor3e.TransactionService.SendAttachmentChunkResponse> SendAttachmentChunkAsync(FacadeFor3e.TransactionService.SendAttachmentChunkRequest request);
        
        // CODEGEN: Parameter 'buffer' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/SendAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FacadeFor3e.TransactionService.SendAttachmentResponse SendAttachment(FacadeFor3e.TransactionService.SendAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/SendAttachment", ReplyAction="*")]
        System.Threading.Tasks.Task<FacadeFor3e.TransactionService.SendAttachmentResponse> SendAttachmentAsync(FacadeFor3e.TransactionService.SendAttachmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetQueryResults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetQueryResults(string archID, string metricID, string objectID, string sessionID, string processItemID, string XPath, string objectData, string quickFindValue, string XOQLStatement, int topRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetQueryResults", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetQueryResultsAsync(string archID, string metricID, string objectID, string sessionID, string processItemID, string XPath, string objectData, string quickFindValue, string XOQLStatement, int topRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetActionsList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetActionsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetActionsList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetActionsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetDataFromArchetypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataFromArchetypes(string paramsXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetDataFromArchetypes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDataFromArchetypesAsync(string paramsXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/UpdatePrintJobStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePrintJobStatus(System.Guid printJobId, FacadeFor3e.TransactionService.ResultCode resultCode, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/UpdatePrintJobStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePrintJobStatusAsync(System.Guid printJobId, FacadeFor3e.TransactionService.ResultCode resultCode, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/UpdateSyncItemTag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateSyncItemTag(string itemIDToSync, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/UpdateSyncItemTag", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateSyncItemTagAsync(string itemIDToSync, string tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetOutOfSyncItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOutOfSyncItems(string LastSyncTime, string Tag, int FirstRows, string ExcludeItemIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetOutOfSyncItems", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetOutOfSyncItemsAsync(string LastSyncTime, string Tag, int FirstRows, string ExcludeItemIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/DoSpellCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DoSpellCheck(string ActionXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/DoSpellCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DoSpellCheckAsync(string ActionXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/CreateModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateModel(string Model, bool IsGlobal, string ProcessID, string PIID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/CreateModel", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreateModelAsync(string Model, bool IsGlobal, string ProcessID, string PIID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/EditModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EditModel(string Model, string Action, bool IsGlobal, string NewModelName, string ProcessID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/EditModel", ReplyAction="*")]
        System.Threading.Tasks.Task<string> EditModelAsync(string Model, string Action, bool IsGlobal, string NewModelName, string ProcessID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMappedItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetMappedItem(string ItemID, string SyncMapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetMappedItem", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetMappedItemAsync(string ItemID, string SyncMapID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetOneNoteMap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOneNoteMap(string MapName, string ItemID, string ArchetypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetOneNoteMap", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetOneNoteMapAsync(string MapName, string ItemID, string ArchetypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetBusinessObjectMethods", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBusinessObjectMethods(string businessObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetBusinessObjectMethods", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBusinessObjectMethodsAsync(string businessObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/StartProcessWithDefaults", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string StartProcessWithDefaults(string defaultsXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/StartProcessWithDefaults", ReplyAction="*")]
        System.Threading.Tasks.Task<string> StartProcessWithDefaultsAsync(string defaultsXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/TEST_GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TEST_GetData(string reportQueryXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/TEST_GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TEST_GetDataAsync(string reportQueryXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/TEST_GetDataFromReportLayout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TEST_GetDataFromReportLayout(string reportLayoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/TEST_GetDataFromReportLayout", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TEST_GetDataFromReportLayoutAsync(string reportLayoutId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/BuildFromClientXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BuildFromClientXML(string clientXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/BuildFromClientXML", ReplyAction="*")]
        System.Threading.Tasks.Task<string> BuildFromClientXMLAsync(string clientXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/ImageConnectDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ImageConnectDelete(string attachmentID, string parentItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/ImageConnectDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ImageConnectDeleteAsync(string attachmentID, string parentItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetOption", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOption(string optionName, FacadeFor3e.TransactionService.DataTypeEnum optionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetOption", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetOptionAsync(string optionName, FacadeFor3e.TransactionService.DataTypeEnum optionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetExpansionCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetExpansionCodes(string[] codes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org//ServiceExecuteProcess/GetExpansionCodes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetExpansionCodesAsync(string[] codes);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess")]
    public enum ReturnInfoType
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Keys,
        
        /// <remarks/>
        Timing,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess")]
    public enum DataOutputFormatType
    {
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        Delimited,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAttachmentChunk", WrapperNamespace="http://tempuri.org//ServiceExecuteProcess", IsWrapped=true)]
    internal partial class SendAttachmentChunkRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=0)]
        public string syncId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=1)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] buffer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=3)]
        public long offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=4)]
        public int bytesRead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=5)]
        public long totalBytes;
        
        public SendAttachmentChunkRequest()
        {
        }
        
        public SendAttachmentChunkRequest(string syncId, string fileName, byte[] buffer, long offset, int bytesRead, long totalBytes)
        {
            this.syncId = syncId;
            this.fileName = fileName;
            this.buffer = buffer;
            this.offset = offset;
            this.bytesRead = bytesRead;
            this.totalBytes = totalBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAttachmentChunkResponse", WrapperNamespace="http://tempuri.org//ServiceExecuteProcess", IsWrapped=true)]
    internal partial class SendAttachmentChunkResponse
    {
        
        public SendAttachmentChunkResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAttachment", WrapperNamespace="http://tempuri.org//ServiceExecuteProcess", IsWrapped=true)]
    internal partial class SendAttachmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=0)]
        public System.Guid itemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=1)]
        public string archetypeID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=2)]
        public string syncId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=3)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] buffer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=5)]
        public long offset;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=6)]
        public int bytesRead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess", Order=7)]
        public long totalBytes;
        
        public SendAttachmentRequest()
        {
        }
        
        public SendAttachmentRequest(System.Guid itemID, string archetypeID, string syncId, string fileName, byte[] buffer, long offset, int bytesRead, long totalBytes)
        {
            this.itemID = itemID;
            this.archetypeID = archetypeID;
            this.syncId = syncId;
            this.fileName = fileName;
            this.buffer = buffer;
            this.offset = offset;
            this.bytesRead = bytesRead;
            this.totalBytes = totalBytes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendAttachmentResponse", WrapperNamespace="http://tempuri.org//ServiceExecuteProcess", IsWrapped=true)]
    internal partial class SendAttachmentResponse
    {
        
        public SendAttachmentResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess")]
    public enum ResultCode
    {
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        StatusUpdate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org//ServiceExecuteProcess")]
    public enum DataTypeEnum
    {
        
        /// <remarks/>
        AUTONUMBER,
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        DATE,
        
        /// <remarks/>
        DATETIME,
        
        /// <remarks/>
        DECIMAL,
        
        /// <remarks/>
        EMAIL,
        
        /// <remarks/>
        FILES,
        
        /// <remarks/>
        GUID,
        
        /// <remarks/>
        INTEGER,
        
        /// <remarks/>
        IMAGE,
        
        /// <remarks/>
        MONEY,
        
        /// <remarks/>
        MULTILANGUAGESTRING,
        
        /// <remarks/>
        NARRATIVE,
        
        /// <remarks/>
        PREDICATE,
        
        /// <remarks/>
        RELATIONSHIP,
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        URL,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface TransactionServiceSoapChannel : FacadeFor3e.TransactionService.TransactionServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class TransactionServiceSoapClient : System.ServiceModel.ClientBase<FacadeFor3e.TransactionService.TransactionServiceSoap>, FacadeFor3e.TransactionService.TransactionServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TransactionServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TransactionServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), TransactionServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TransactionServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TransactionServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TransactionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public FacadeFor3e.TransactionService.ReturnInfoType ExposeEnum(string processXML, int returnInfo)
        {
            return base.Channel.ExposeEnum(processXML, returnInfo);
        }
        
        public System.Threading.Tasks.Task<FacadeFor3e.TransactionService.ReturnInfoType> ExposeEnumAsync(string processXML, int returnInfo)
        {
            return base.Channel.ExposeEnumAsync(processXML, returnInfo);
        }
        
        public string GetServiceTimeZoneID()
        {
            return base.Channel.GetServiceTimeZoneID();
        }
        
        public System.Threading.Tasks.Task<string> GetServiceTimeZoneIDAsync()
        {
            return base.Channel.GetServiceTimeZoneIDAsync();
        }
        
        public string GetServiceCulture()
        {
            return base.Channel.GetServiceCulture();
        }
        
        public System.Threading.Tasks.Task<string> GetServiceCultureAsync()
        {
            return base.Channel.GetServiceCultureAsync();
        }
        
        public string ExecuteProcess(string processXML, int returnInfo)
        {
            return base.Channel.ExecuteProcess(processXML, returnInfo);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteProcessAsync(string processXML, int returnInfo)
        {
            return base.Channel.ExecuteProcessAsync(processXML, returnInfo);
        }
        
        public string GetAppObjectSecurityRights(string projectXML)
        {
            return base.Channel.GetAppObjectSecurityRights(projectXML);
        }
        
        public System.Threading.Tasks.Task<string> GetAppObjectSecurityRightsAsync(string projectXML)
        {
            return base.Channel.GetAppObjectSecurityRightsAsync(projectXML);
        }
        
        public string CancelAllOpenProcesses()
        {
            return base.Channel.CancelAllOpenProcesses();
        }
        
        public System.Threading.Tasks.Task<string> CancelAllOpenProcessesAsync()
        {
            return base.Channel.CancelAllOpenProcessesAsync();
        }
        
        public string GetArchetypeDataGlobal(string selectXml, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetArchetypeDataGlobal(selectXml, outputFormatType, delimiterChar, includeHeaders);
        }
        
        public System.Threading.Tasks.Task<string> GetArchetypeDataGlobalAsync(string selectXml, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetArchetypeDataGlobalAsync(selectXml, outputFormatType, delimiterChar, includeHeaders);
        }
        
        public string GetMetricDataGlobal(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetMetricDataGlobal(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID, outputFormatType, delimiterChar, includeHeaders);
        }
        
        public System.Threading.Tasks.Task<string> GetMetricDataGlobalAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetMetricDataGlobalAsync(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID, outputFormatType, delimiterChar, includeHeaders);
        }
        
        public string GetNamedMetricDataGlobal(string selectXml, string metricTableName, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetNamedMetricDataGlobal(selectXml, metricTableName, outputFormatType, delimiterChar, includeHeaders);
        }
        
        public System.Threading.Tasks.Task<string> GetNamedMetricDataGlobalAsync(string selectXml, string metricTableName, FacadeFor3e.TransactionService.DataOutputFormatType outputFormatType, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetNamedMetricDataGlobalAsync(selectXml, metricTableName, outputFormatType, delimiterChar, includeHeaders);
        }
        
        public string GetFormattedArchetypeData(string selectXml, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetFormattedArchetypeData(selectXml, delimiterChar, includeHeaders);
        }
        
        public System.Threading.Tasks.Task<string> GetFormattedArchetypeDataAsync(string selectXml, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetFormattedArchetypeDataAsync(selectXml, delimiterChar, includeHeaders);
        }
        
        public string GetArchetypeData(string selectXml)
        {
            return base.Channel.GetArchetypeData(selectXml);
        }
        
        public System.Threading.Tasks.Task<string> GetArchetypeDataAsync(string selectXml)
        {
            return base.Channel.GetArchetypeDataAsync(selectXml);
        }
        
        public string GetFormattedMetricData(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetFormattedMetricData(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID, delimiterChar, includeHeaders);
        }
        
        public System.Threading.Tasks.Task<string> GetFormattedMetricDataAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetFormattedMetricDataAsync(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID, delimiterChar, includeHeaders);
        }
        
        public string GetMetricData(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID)
        {
            return base.Channel.GetMetricData(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID);
        }
        
        public System.Threading.Tasks.Task<string> GetMetricDataAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID)
        {
            return base.Channel.GetMetricDataAsync(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID);
        }
        
        public string GetFormattedNamedMetricData(string selectXml, string metricTableName, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetFormattedNamedMetricData(selectXml, metricTableName, delimiterChar, includeHeaders);
        }
        
        public System.Threading.Tasks.Task<string> GetFormattedNamedMetricDataAsync(string selectXml, string metricTableName, string delimiterChar, bool includeHeaders)
        {
            return base.Channel.GetFormattedNamedMetricDataAsync(selectXml, metricTableName, delimiterChar, includeHeaders);
        }
        
        public string GetNamedMetricData(string selectXml, string metricTableName)
        {
            return base.Channel.GetNamedMetricData(selectXml, metricTableName);
        }
        
        public System.Threading.Tasks.Task<string> GetNamedMetricDataAsync(string selectXml, string metricTableName)
        {
            return base.Channel.GetNamedMetricDataAsync(selectXml, metricTableName);
        }
        
        public string GetArchetypeDataSQL(string selectXml)
        {
            return base.Channel.GetArchetypeDataSQL(selectXml);
        }
        
        public System.Threading.Tasks.Task<string> GetArchetypeDataSQLAsync(string selectXml)
        {
            return base.Channel.GetArchetypeDataSQLAsync(selectXml);
        }
        
        public string GetMetricDataSQL(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID)
        {
            return base.Channel.GetMetricDataSQL(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID);
        }
        
        public System.Threading.Tasks.Task<string> GetMetricDataSQLAsync(string selectXml, int metricRunIndex, bool isRunIndexRelative, string metricGroupID)
        {
            return base.Channel.GetMetricDataSQLAsync(selectXml, metricRunIndex, isRunIndexRelative, metricGroupID);
        }
        
        public string GetNamedMetricDataSQL(string selectXml, string metricTableName)
        {
            return base.Channel.GetNamedMetricDataSQL(selectXml, metricTableName);
        }
        
        public System.Threading.Tasks.Task<string> GetNamedMetricDataSQLAsync(string selectXml, string metricTableName)
        {
            return base.Channel.GetNamedMetricDataSQLAsync(selectXml, metricTableName);
        }
        
        public string GetData(string reportQueryXML)
        {
            return base.Channel.GetData(reportQueryXML);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string reportQueryXML)
        {
            return base.Channel.GetDataAsync(reportQueryXML);
        }
        
        public string GetDataFromReportLayout(string reportLayoutId)
        {
            return base.Channel.GetDataFromReportLayout(reportLayoutId);
        }
        
        public System.Threading.Tasks.Task<string> GetDataFromReportLayoutAsync(string reportLayoutId)
        {
            return base.Channel.GetDataFromReportLayoutAsync(reportLayoutId);
        }
        
        public string GetDataFromReportLayoutCrystal(string reportLayoutId)
        {
            return base.Channel.GetDataFromReportLayoutCrystal(reportLayoutId);
        }
        
        public System.Threading.Tasks.Task<string> GetDataFromReportLayoutCrystalAsync(string reportLayoutId)
        {
            return base.Channel.GetDataFromReportLayoutCrystalAsync(reportLayoutId);
        }
        
        public string[] GetSyncIds()
        {
            return base.Channel.GetSyncIds();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSyncIdsAsync()
        {
            return base.Channel.GetSyncIdsAsync();
        }
        
        public string CheckFileHash(string syncId)
        {
            return base.Channel.CheckFileHash(syncId);
        }
        
        public System.Threading.Tasks.Task<string> CheckFileHashAsync(string syncId)
        {
            return base.Channel.CheckFileHashAsync(syncId);
        }
        
        public void Ping()
        {
            base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task PingAsync()
        {
            return base.Channel.PingAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacadeFor3e.TransactionService.SendAttachmentChunkResponse FacadeFor3e.TransactionService.TransactionServiceSoap.SendAttachmentChunk(FacadeFor3e.TransactionService.SendAttachmentChunkRequest request)
        {
            return base.Channel.SendAttachmentChunk(request);
        }
        
        public void SendAttachmentChunk(string syncId, string fileName, byte[] buffer, long offset, int bytesRead, long totalBytes)
        {
            FacadeFor3e.TransactionService.SendAttachmentChunkRequest inValue = new FacadeFor3e.TransactionService.SendAttachmentChunkRequest();
            inValue.syncId = syncId;
            inValue.fileName = fileName;
            inValue.buffer = buffer;
            inValue.offset = offset;
            inValue.bytesRead = bytesRead;
            inValue.totalBytes = totalBytes;
            FacadeFor3e.TransactionService.SendAttachmentChunkResponse retVal = ((FacadeFor3e.TransactionService.TransactionServiceSoap)(this)).SendAttachmentChunk(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacadeFor3e.TransactionService.SendAttachmentChunkResponse> FacadeFor3e.TransactionService.TransactionServiceSoap.SendAttachmentChunkAsync(FacadeFor3e.TransactionService.SendAttachmentChunkRequest request)
        {
            return base.Channel.SendAttachmentChunkAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeFor3e.TransactionService.SendAttachmentChunkResponse> SendAttachmentChunkAsync(string syncId, string fileName, byte[] buffer, long offset, int bytesRead, long totalBytes)
        {
            FacadeFor3e.TransactionService.SendAttachmentChunkRequest inValue = new FacadeFor3e.TransactionService.SendAttachmentChunkRequest();
            inValue.syncId = syncId;
            inValue.fileName = fileName;
            inValue.buffer = buffer;
            inValue.offset = offset;
            inValue.bytesRead = bytesRead;
            inValue.totalBytes = totalBytes;
            return ((FacadeFor3e.TransactionService.TransactionServiceSoap)(this)).SendAttachmentChunkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FacadeFor3e.TransactionService.SendAttachmentResponse FacadeFor3e.TransactionService.TransactionServiceSoap.SendAttachment(FacadeFor3e.TransactionService.SendAttachmentRequest request)
        {
            return base.Channel.SendAttachment(request);
        }
        
        public void SendAttachment(System.Guid itemID, string archetypeID, string syncId, string fileName, byte[] buffer, long offset, int bytesRead, long totalBytes)
        {
            FacadeFor3e.TransactionService.SendAttachmentRequest inValue = new FacadeFor3e.TransactionService.SendAttachmentRequest();
            inValue.itemID = itemID;
            inValue.archetypeID = archetypeID;
            inValue.syncId = syncId;
            inValue.fileName = fileName;
            inValue.buffer = buffer;
            inValue.offset = offset;
            inValue.bytesRead = bytesRead;
            inValue.totalBytes = totalBytes;
            FacadeFor3e.TransactionService.SendAttachmentResponse retVal = ((FacadeFor3e.TransactionService.TransactionServiceSoap)(this)).SendAttachment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FacadeFor3e.TransactionService.SendAttachmentResponse> FacadeFor3e.TransactionService.TransactionServiceSoap.SendAttachmentAsync(FacadeFor3e.TransactionService.SendAttachmentRequest request)
        {
            return base.Channel.SendAttachmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FacadeFor3e.TransactionService.SendAttachmentResponse> SendAttachmentAsync(System.Guid itemID, string archetypeID, string syncId, string fileName, byte[] buffer, long offset, int bytesRead, long totalBytes)
        {
            FacadeFor3e.TransactionService.SendAttachmentRequest inValue = new FacadeFor3e.TransactionService.SendAttachmentRequest();
            inValue.itemID = itemID;
            inValue.archetypeID = archetypeID;
            inValue.syncId = syncId;
            inValue.fileName = fileName;
            inValue.buffer = buffer;
            inValue.offset = offset;
            inValue.bytesRead = bytesRead;
            inValue.totalBytes = totalBytes;
            return ((FacadeFor3e.TransactionService.TransactionServiceSoap)(this)).SendAttachmentAsync(inValue);
        }
        
        public string GetQueryResults(string archID, string metricID, string objectID, string sessionID, string processItemID, string XPath, string objectData, string quickFindValue, string XOQLStatement, int topRows)
        {
            return base.Channel.GetQueryResults(archID, metricID, objectID, sessionID, processItemID, XPath, objectData, quickFindValue, XOQLStatement, topRows);
        }
        
        public System.Threading.Tasks.Task<string> GetQueryResultsAsync(string archID, string metricID, string objectID, string sessionID, string processItemID, string XPath, string objectData, string quickFindValue, string XOQLStatement, int topRows)
        {
            return base.Channel.GetQueryResultsAsync(archID, metricID, objectID, sessionID, processItemID, XPath, objectData, quickFindValue, XOQLStatement, topRows);
        }
        
        public string GetActionsList()
        {
            return base.Channel.GetActionsList();
        }
        
        public System.Threading.Tasks.Task<string> GetActionsListAsync()
        {
            return base.Channel.GetActionsListAsync();
        }
        
        public string GetDataFromArchetypes(string paramsXML)
        {
            return base.Channel.GetDataFromArchetypes(paramsXML);
        }
        
        public System.Threading.Tasks.Task<string> GetDataFromArchetypesAsync(string paramsXML)
        {
            return base.Channel.GetDataFromArchetypesAsync(paramsXML);
        }
        
        public string UpdatePrintJobStatus(System.Guid printJobId, FacadeFor3e.TransactionService.ResultCode resultCode, string msg)
        {
            return base.Channel.UpdatePrintJobStatus(printJobId, resultCode, msg);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePrintJobStatusAsync(System.Guid printJobId, FacadeFor3e.TransactionService.ResultCode resultCode, string msg)
        {
            return base.Channel.UpdatePrintJobStatusAsync(printJobId, resultCode, msg);
        }
        
        public string UpdateSyncItemTag(string itemIDToSync, string tag)
        {
            return base.Channel.UpdateSyncItemTag(itemIDToSync, tag);
        }
        
        public System.Threading.Tasks.Task<string> UpdateSyncItemTagAsync(string itemIDToSync, string tag)
        {
            return base.Channel.UpdateSyncItemTagAsync(itemIDToSync, tag);
        }
        
        public string GetOutOfSyncItems(string LastSyncTime, string Tag, int FirstRows, string ExcludeItemIDList)
        {
            return base.Channel.GetOutOfSyncItems(LastSyncTime, Tag, FirstRows, ExcludeItemIDList);
        }
        
        public System.Threading.Tasks.Task<string> GetOutOfSyncItemsAsync(string LastSyncTime, string Tag, int FirstRows, string ExcludeItemIDList)
        {
            return base.Channel.GetOutOfSyncItemsAsync(LastSyncTime, Tag, FirstRows, ExcludeItemIDList);
        }
        
        public string DoSpellCheck(string ActionXML)
        {
            return base.Channel.DoSpellCheck(ActionXML);
        }
        
        public System.Threading.Tasks.Task<string> DoSpellCheckAsync(string ActionXML)
        {
            return base.Channel.DoSpellCheckAsync(ActionXML);
        }
        
        public string CreateModel(string Model, bool IsGlobal, string ProcessID, string PIID)
        {
            return base.Channel.CreateModel(Model, IsGlobal, ProcessID, PIID);
        }
        
        public System.Threading.Tasks.Task<string> CreateModelAsync(string Model, bool IsGlobal, string ProcessID, string PIID)
        {
            return base.Channel.CreateModelAsync(Model, IsGlobal, ProcessID, PIID);
        }
        
        public string EditModel(string Model, string Action, bool IsGlobal, string NewModelName, string ProcessID)
        {
            return base.Channel.EditModel(Model, Action, IsGlobal, NewModelName, ProcessID);
        }
        
        public System.Threading.Tasks.Task<string> EditModelAsync(string Model, string Action, bool IsGlobal, string NewModelName, string ProcessID)
        {
            return base.Channel.EditModelAsync(Model, Action, IsGlobal, NewModelName, ProcessID);
        }
        
        public string GetMappedItem(string ItemID, string SyncMapID)
        {
            return base.Channel.GetMappedItem(ItemID, SyncMapID);
        }
        
        public System.Threading.Tasks.Task<string> GetMappedItemAsync(string ItemID, string SyncMapID)
        {
            return base.Channel.GetMappedItemAsync(ItemID, SyncMapID);
        }
        
        public string GetOneNoteMap(string MapName, string ItemID, string ArchetypeID)
        {
            return base.Channel.GetOneNoteMap(MapName, ItemID, ArchetypeID);
        }
        
        public System.Threading.Tasks.Task<string> GetOneNoteMapAsync(string MapName, string ItemID, string ArchetypeID)
        {
            return base.Channel.GetOneNoteMapAsync(MapName, ItemID, ArchetypeID);
        }
        
        public string GetBusinessObjectMethods(string businessObject)
        {
            return base.Channel.GetBusinessObjectMethods(businessObject);
        }
        
        public System.Threading.Tasks.Task<string> GetBusinessObjectMethodsAsync(string businessObject)
        {
            return base.Channel.GetBusinessObjectMethodsAsync(businessObject);
        }
        
        public string StartProcessWithDefaults(string defaultsXML)
        {
            return base.Channel.StartProcessWithDefaults(defaultsXML);
        }
        
        public System.Threading.Tasks.Task<string> StartProcessWithDefaultsAsync(string defaultsXML)
        {
            return base.Channel.StartProcessWithDefaultsAsync(defaultsXML);
        }
        
        public string TEST_GetData(string reportQueryXML)
        {
            return base.Channel.TEST_GetData(reportQueryXML);
        }
        
        public System.Threading.Tasks.Task<string> TEST_GetDataAsync(string reportQueryXML)
        {
            return base.Channel.TEST_GetDataAsync(reportQueryXML);
        }
        
        public string TEST_GetDataFromReportLayout(string reportLayoutId)
        {
            return base.Channel.TEST_GetDataFromReportLayout(reportLayoutId);
        }
        
        public System.Threading.Tasks.Task<string> TEST_GetDataFromReportLayoutAsync(string reportLayoutId)
        {
            return base.Channel.TEST_GetDataFromReportLayoutAsync(reportLayoutId);
        }
        
        public string BuildFromClientXML(string clientXML)
        {
            return base.Channel.BuildFromClientXML(clientXML);
        }
        
        public System.Threading.Tasks.Task<string> BuildFromClientXMLAsync(string clientXML)
        {
            return base.Channel.BuildFromClientXMLAsync(clientXML);
        }
        
        public string ImageConnectDelete(string attachmentID, string parentItemID)
        {
            return base.Channel.ImageConnectDelete(attachmentID, parentItemID);
        }
        
        public System.Threading.Tasks.Task<string> ImageConnectDeleteAsync(string attachmentID, string parentItemID)
        {
            return base.Channel.ImageConnectDeleteAsync(attachmentID, parentItemID);
        }
        
        public string GetOption(string optionName, FacadeFor3e.TransactionService.DataTypeEnum optionType)
        {
            return base.Channel.GetOption(optionName, optionType);
        }
        
        public System.Threading.Tasks.Task<string> GetOptionAsync(string optionName, FacadeFor3e.TransactionService.DataTypeEnum optionType)
        {
            return base.Channel.GetOptionAsync(optionName, optionType);
        }
        
        public string GetExpansionCodes(string[] codes)
        {
            return base.Channel.GetExpansionCodes(codes);
        }
        
        public System.Threading.Tasks.Task<string> GetExpansionCodesAsync(string[] codes)
        {
            return base.Channel.GetExpansionCodesAsync(codes);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TransactionServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TransactionServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TransactionServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://lon0203489/TE_3E_Dev/WebUI/TransactionService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TransactionServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://lon0203489/TE_3E_Dev/WebUI/TransactionService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TransactionServiceSoap,
            
            TransactionServiceSoap12,
        }
    }
}
