using System;
using System.Collections.Generic;
using System.Xml;
using JetBrains.Annotations;

namespace FacadeFor3e
    {
    [PublicAPI]
    public class RunProcessResult
        {
        internal RunProcessResult(XmlDocument request, XmlDocument response)
            {
            if (request?.DocumentElement == null)
                throw new ArgumentException("Invalid request.", nameof(request));
            if (response?.DocumentElement == null)
                throw new ArgumentException("Invalid response.", nameof(response));

            this.Request = request;
            this.Response = response;
            }

        /// <summary>
        /// Gets the request sent to 3e
        /// </summary>
        public XmlDocument Request { get; }

        /// <summary>
        /// Gets the response from 3e
        /// </summary>
        public XmlDocument Response { get; }

        /// <summary>
        /// Gets the process ID that was used to run the request
        /// </summary>
        /// <remarks>This corresponds to a row in the NxFwkProcessItem table identified by the ProcItemID column</remarks>
        public Guid ProcessId
            {
            get
                {
                // ReSharper disable once PossibleNullReferenceException
                var result = new Guid(this.Response.DocumentElement.GetAttribute("ProcessItemId"));
                return result;
                }
            }

        /// <summary>
        /// Gets the final output ID the process used before it ended
        /// </summary>
        /// <remarks>Sometimes this can be useful to determine what path the process took, and even whether it actually failed when it appeared to succeed</remarks>
        public string OutputId
            {
            get
                {
                // ReSharper disable once PossibleNullReferenceException
                var result = this.Response.DocumentElement.GetAttribute("OutputId");
                return result;
                }
            }

        /// <summary>
        /// Returns any notification messages generated by the process
        /// </summary>
        public string NextMessage
            {
            get
                {
                // ReSharper disable once PossibleNullReferenceException
                var nextMessage = this.Response.DocumentElement.SelectSingleNode("MESSAGE");
                var result = nextMessage?.InnerText;
                return result;
                }
            }

        /// <summary>
        /// Returns the primary keys of any new records created by the process
        /// </summary>
        /// <returns></returns>
        public IEnumerable<string> GetKeys()
            {
            var keys = this.Response.SelectSingleNode("ProcessExecutionResults/Keys");
            if (keys == null)
                // The presence of the Keys node is dependent only upon whether ReturnInfoType.Keys was specified when calling ExecuteProcess 
                throw new InvalidOperationException("Key information was not requested.");

            foreach (XmlElement node in keys.ChildNodes)
                {
                string result = node.GetAttribute("KeyValue");
                yield return result;
                }
            }
        }
    }
